#############################################################################
# Makefile for building: moonlight-qt
# Generated by qmake (3.1) (Qt 5.15.18)
# Project:  moonlight-qt.pro
# Template: subdirs
# Command: /opt/homebrew/opt/qt@5/bin/qmake -o Makefile moonlight-qt.pro -config debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /opt/homebrew/opt/qt@5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/opt/qt@5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/opt/qt@5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = moonlight-qt1.0.0
DISTDIR = /Users/nguyenquoc/Downloads/goslynk-cloud/.tmp/moonlight-qt1.0.0
SUBTARGETS    =  \
		sub-moonlight-common-c \
		sub-qmdnsengine \
		sub-app \
		sub-h264bitstream


####### Custom Variables
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-qt.pro

sub-moonlight-common-c-qmake_all:  FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug
	cd moonlight-common-c/ && $(MAKE) -f Makefile qmake_all
sub-moonlight-common-c: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile
sub-moonlight-common-c-make_first: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile 
sub-moonlight-common-c-all: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile all
sub-moonlight-common-c-clean: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile clean
sub-moonlight-common-c-distclean: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile distclean
sub-moonlight-common-c-install_subtargets: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile install
sub-moonlight-common-c-uninstall_subtargets: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile uninstall
sub-qmdnsengine-qmake_all:  FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug
	cd qmdnsengine/ && $(MAKE) -f Makefile qmake_all
sub-qmdnsengine: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile
sub-qmdnsengine-make_first: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile 
sub-qmdnsengine-all: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile all
sub-qmdnsengine-clean: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile clean
sub-qmdnsengine-distclean: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile distclean
sub-qmdnsengine-install_subtargets: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile install
sub-qmdnsengine-uninstall_subtargets: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-qmdnsengine-qmake_all sub-moonlight-common-c-qmake_all sub-h264bitstream-qmake_all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug
	cd app/ && $(MAKE) -f Makefile qmake_all
sub-app: sub-qmdnsengine \
		sub-moonlight-common-c \
		sub-h264bitstream FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile
sub-app-make_first: sub-qmdnsengine-make_first sub-moonlight-common-c-make_first sub-h264bitstream-make_first FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile 
sub-app-all: sub-qmdnsengine-all sub-moonlight-common-c-all sub-h264bitstream-all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile all
sub-app-clean: sub-qmdnsengine-clean sub-moonlight-common-c-clean sub-h264bitstream-clean FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile clean
sub-app-distclean: sub-qmdnsengine-distclean sub-moonlight-common-c-distclean sub-h264bitstream-distclean FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets: sub-qmdnsengine-install_subtargets sub-moonlight-common-c-install_subtargets sub-h264bitstream-install_subtargets FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets: sub-qmdnsengine-uninstall_subtargets sub-moonlight-common-c-uninstall_subtargets sub-h264bitstream-uninstall_subtargets FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile uninstall
sub-h264bitstream-qmake_all:  FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug
	cd h264bitstream/ && $(MAKE) -f Makefile qmake_all
sub-h264bitstream: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile
sub-h264bitstream-make_first: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile 
sub-h264bitstream-all: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile all
sub-h264bitstream-clean: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile clean
sub-h264bitstream-distclean: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile distclean
sub-h264bitstream-install_subtargets: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile install
sub-h264bitstream-uninstall_subtargets: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile uninstall

Makefile: moonlight-qt.pro .qmake.cache /opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/configure_base.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/configure.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/exclusive_builds_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/lex.prf \
		moonlight-qt.pro
	$(QMAKE) -o Makefile moonlight-qt.pro -config debug
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/configure_base.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/configure.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/exclusive_builds_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.18/mkspecs/features/lex.prf:
moonlight-qt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile moonlight-qt.pro -config debug

qmake_all: sub-moonlight-common-c-qmake_all sub-qmdnsengine-qmake_all sub-app-qmake_all sub-h264bitstream-qmake_all FORCE

make_first: sub-moonlight-common-c-make_first sub-qmdnsengine-make_first sub-app-make_first sub-h264bitstream-make_first  FORCE
all: sub-moonlight-common-c-all sub-qmdnsengine-all sub-app-all sub-h264bitstream-all  FORCE
clean: sub-moonlight-common-c-clean sub-qmdnsengine-clean sub-app-clean sub-h264bitstream-clean  FORCE
distclean: sub-moonlight-common-c-distclean sub-qmdnsengine-distclean sub-app-distclean sub-h264bitstream-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-moonlight-common-c-install_subtargets sub-qmdnsengine-install_subtargets sub-app-install_subtargets sub-h264bitstream-install_subtargets FORCE
uninstall_subtargets: sub-moonlight-common-c-uninstall_subtargets sub-qmdnsengine-uninstall_subtargets sub-app-uninstall_subtargets sub-h264bitstream-uninstall_subtargets FORCE

sub-moonlight-common-c-debug:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile debug
sub-qmdnsengine-debug:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile debug
sub-app-debug: sub-qmdnsengine-debug sub-moonlight-common-c-debug sub-h264bitstream-debug
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile debug
sub-h264bitstream-debug:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile debug
debug: sub-moonlight-common-c-debug sub-qmdnsengine-debug sub-app-debug sub-h264bitstream-debug

sub-moonlight-common-c-release:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile release
sub-qmdnsengine-release:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile release
sub-app-release: sub-qmdnsengine-release sub-moonlight-common-c-release sub-h264bitstream-release
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile release
sub-h264bitstream-release:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile release
release: sub-moonlight-common-c-release sub-qmdnsengine-release sub-app-release sub-h264bitstream-release

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -config debug

sub-moonlight-common-c-check:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile check
sub-qmdnsengine-check:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile check
sub-app-check: sub-qmdnsengine-check sub-moonlight-common-c-check sub-h264bitstream-check
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile check
sub-h264bitstream-check:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile check
check: sub-moonlight-common-c-check sub-qmdnsengine-check sub-app-check sub-h264bitstream-check

sub-moonlight-common-c-benchmark:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -f Makefile benchmark
sub-qmdnsengine-benchmark:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -f Makefile benchmark
sub-app-benchmark: sub-qmdnsengine-benchmark sub-moonlight-common-c-benchmark sub-h264bitstream-benchmark
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -f Makefile benchmark
sub-h264bitstream-benchmark:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -f Makefile benchmark
benchmark: sub-moonlight-common-c-benchmark sub-qmdnsengine-benchmark sub-app-benchmark sub-h264bitstream-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-moonlight-common-c-distdir sub-qmdnsengine-distdir sub-app-distdir sub-h264bitstream-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.stash moonlight-qt.pro $(DISTDIR)/

sub-moonlight-common-c-distdir: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/moonlight-common-c/moonlight-common-c.pro -config debug ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/moonlight-common-c

sub-qmdnsengine-distdir: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/qmdnsengine/qmdnsengine.pro -config debug ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/qmdnsengine

sub-app-distdir: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/app/app.pro -config debug ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/app

sub-h264bitstream-distdir: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/nguyenquoc/Downloads/goslynk-cloud/h264bitstream/h264bitstream.pro -config debug ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/h264bitstream

